### ISSUE TITLE
Pack won't install/compile on macOS Apple Silicon

### ISSUE THREAD

**Issue by curtosis** [terminusdb/terminus_store_prolog#20]
The `$SWIARCH` test in the Makefile only matches on `x86_64-darwin`, so it tries to build using the default (Linux) `$BUILD_LD_OPTIONS`. These options aren't understood by the XCode linker, so the build fails.

I tried adding an `arm64-darwin` test arm that uses the same `$BUILD_LD_OPTIONS`; that build succeeds and passes the tests.

I'm not sure whether the "correct" fix would be to switch on `$SWIARCH` or `$OS`, though, since I don't know the reasons why the Darwin test is architecture-specific.

**Comment by rrooij** [comment]
Can you perhaps make a pull request if you want to? I usually test the Mac OS versions in a VM but for the M1 chips that will turn out to be a bit trickier. If the same build flags work, then switching on OS instead of SWIARCH is probably better.

We haven't tested a lot on ARM architectures by the way but so far we haven't encountered any specific issues.

**Comment by curtosis** [comment]
Sure thing. I'll put a PR together today(ish).
